version: 0.0
os: linux
files:
  - source: /target/CounterWebApp.war
    destination: /var/lib/tomcat8/webapps
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
